package com.periodizeai.app.services

import com.periodizeai.app.models.*
import com.periodizeai.app.repositories.ExerciseData

object ExerciseCatalogService {

    fun getCatalog(): List<ExerciseData> = allExercises().map { exercise ->
        val tags = stickingPointTags[exercise.name] ?: emptyList()
        if (tags.isEmpty()) exercise else exercise.copy(addressesStickingPoints = tags)
    }

    fun findExercise(name: String, exercises: List<ExerciseData>): ExerciseData? {
        val trimmed = name.trim()
        val mapped = csvExerciseMapping[trimmed]
        if (mapped != null) return exercises.firstOrNull { it.name == mapped }
        return exercises.firstOrNull { it.name.lowercase() == trimmed.lowercase() }
    }

    fun findSwapCandidates(
        exercise: ExerciseData,
        allExercises: List<ExerciseData>,
        stickingPoints: List<StickingPoint> = emptyList(),
    ): Pair<List<ExerciseData>, List<ExerciseData>> {
        val recommended = allExercises
            .filter { candidate ->
                candidate.name != exercise.name &&
                candidate.primaryMuscles.any { exercise.primaryMuscles.contains(it) }
            }
            .sortedWith(compareBy(
                { it.movementPattern != exercise.movementPattern },
                { if (stickingPoints.isNotEmpty()) !it.addressesStickingPoints.any { sp -> stickingPoints.contains(sp) } else false },
                { it.classification != exercise.classification },
                { it.name },
            ))
        val all = allExercises.filter { it.name != exercise.name }.sortedBy { it.name }
        return Pair(recommended, all)
    }

    val stickingPointTags: Map<String, List<StickingPoint>> = mapOf(
        "Pause Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_BACK),
        "Pause High Bar Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE),
        "Front Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_LEGS),
        "Tempo Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE),
        "Safety Bar Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_BACK, StickingPoint.SQUAT_UPPER_BACK_ROUNDING),
        "High Bar Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_LEGS),
        "Pin Squat" to listOf(StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_LOCKOUT),
        "Box Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_BACK),
        "Zercher Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_UPPER_BACK_ROUNDING),
        "Belt Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_LEGS),
        "Leg Press" to listOf(StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_LEGS),
        "Pause Leg Press" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_LEGS),
        "Hack Squat" to listOf(StickingPoint.SQUAT_MID_RANGE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_LEGS),
        "Bulgarian Split Squat" to listOf(StickingPoint.SQUAT_OUT_OF_HOLE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_LEGS),
        "Back Raise" to listOf(StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_BACK),
        "Reverse Hyperextension" to listOf(StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_BACK),
        "Good Mornings" to listOf(StickingPoint.DEADLIFT_BELOW_KNEE, StickingPoint.SQUAT_ABOVE_PARALLEL_WEAK_BACK),
        "Barbell Row" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR, StickingPoint.SQUAT_UPPER_BACK_ROUNDING),
        "Pendlay Row" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR, StickingPoint.SQUAT_UPPER_BACK_ROUNDING),
        "Chest Supported Rows" to listOf(StickingPoint.SQUAT_UPPER_BACK_ROUNDING),
        "Pause Bench Press" to listOf(StickingPoint.BENCH_OFF_CHEST),
        "3 Count Pause Bench" to listOf(StickingPoint.BENCH_OFF_CHEST),
        "Spoto Press" to listOf(StickingPoint.BENCH_OFF_CHEST, StickingPoint.BENCH_MID_RANGE),
        "Wide Grip Bench Press" to listOf(StickingPoint.BENCH_OFF_CHEST),
        "Extra Wide Bench Press" to listOf(StickingPoint.BENCH_OFF_CHEST),
        "Larsen Press" to listOf(StickingPoint.BENCH_OFF_CHEST),
        "Feet Up Bench" to listOf(StickingPoint.BENCH_OFF_CHEST),
        "Tempo Bench Press" to listOf(StickingPoint.BENCH_OFF_CHEST, StickingPoint.BENCH_MID_RANGE),
        "Incline Bench Press" to listOf(StickingPoint.BENCH_OFF_CHEST, StickingPoint.BENCH_MID_RANGE),
        "Decline Bench Press" to listOf(StickingPoint.BENCH_MID_RANGE),
        "Close Grip Bench Press" to listOf(StickingPoint.BENCH_MID_RANGE, StickingPoint.BENCH_LOCKOUT),
        "Floor Press" to listOf(StickingPoint.BENCH_MID_RANGE, StickingPoint.BENCH_LOCKOUT),
        "DB Floor Press" to listOf(StickingPoint.BENCH_MID_RANGE, StickingPoint.BENCH_LOCKOUT),
        "Pin Press" to listOf(StickingPoint.BENCH_MID_RANGE, StickingPoint.BENCH_LOCKOUT),
        "JM Press" to listOf(StickingPoint.BENCH_MID_RANGE, StickingPoint.BENCH_LOCKOUT),
        "Tate Press" to listOf(StickingPoint.BENCH_LOCKOUT),
        "Dips" to listOf(StickingPoint.BENCH_LOCKOUT),
        "Weighted Dips" to listOf(StickingPoint.BENCH_LOCKOUT),
        "Conv Deficit Deadlift" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR),
        "Sumo Deficit Deadlift" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR),
        "Double Overhand Deficit Deadlift" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR),
        "Pause Off Floor Deadlift" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR),
        "Halting Conventional Deadlift" to listOf(StickingPoint.DEADLIFT_BELOW_KNEE),
        "Halting Sumo Deadlift" to listOf(StickingPoint.DEADLIFT_BELOW_KNEE),
        "Block Pull" to listOf(StickingPoint.DEADLIFT_LOCKOUT),
        "Reverse Band Deadlift" to listOf(StickingPoint.DEADLIFT_LOCKOUT),
        "Trap Bar Deadlift" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR),
        "RDLs" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR, StickingPoint.DEADLIFT_BELOW_KNEE),
        "Stiff Leg Deadlift" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR),
        "Barbell Hip Thrust" to listOf(StickingPoint.DEADLIFT_LOCKOUT, StickingPoint.SQUAT_LOCKOUT),
        "Glute Bridge" to listOf(StickingPoint.DEADLIFT_LOCKOUT, StickingPoint.SQUAT_LOCKOUT),
        "Conventional Deadlift" to listOf(StickingPoint.DEADLIFT_OFF_FLOOR),
        "Sumo Deadlift" to listOf(StickingPoint.DEADLIFT_BELOW_KNEE),
    )

    val csvExerciseMapping: Map<String, String> = mapOf(
        "Comp Squat" to "Comp Squat",
        "Front Squat" to "Front Squat",
        "High Bar Squat" to "High Bar Squat",
        "Pause Squat" to "Pause Squat",
        "Pause High Bar Squat" to "Pause High Bar Squat",
        "Tempo Squat (5:0:0)" to "Tempo Squat",
        "Box Squat" to "Box Squat",
        "Goblet Squat" to "Goblet Squat",
        "Band Around Knees Goblet Squat" to "Band Around Knees Goblet Squat",
        "Leg Press/Hack Squat" to "Leg Press",
        "Pause Leg Press/Hack Squat" to "Pause Leg Press",
        "SL Leg Press/Hack Squat" to "Single Leg Leg Press",
        "Split Squat (Quad Emphasis)" to "Split Squat (Quad Emphasis)",
        "Bulgarian Split Squat" to "Bulgarian Split Squat",
        "Lunges" to "Lunges",
        "Walking Lunges" to "Walking Lunges",
        "Step Ups" to "Step Ups",
        "Leg Extensions" to "Leg Extensions",
        "Comp Deadlift" to "Comp Deadlift",
        "Conventional Deadlift" to "Conventional Deadlift",
        "Sumo Deadlift" to "Sumo Deadlift",
        "1\" Conv Deficit Deadlift" to "Conv Deficit Deadlift",
        "1\"\" Conv Deficit Deadlift" to "Conv Deficit Deadlift",
        "Double Overhand 1\"\" Conv Deficit Deadlift" to "Double Overhand Deficit Deadlift",
        "Double Overhand 1\" Conv Deficit Deadlift" to "Double Overhand Deficit Deadlift",
        "Halting Conventional Deadlift" to "Halting Conventional Deadlift",
        "Halting Sumo Deadlift" to "Halting Sumo Deadlift",
        "Pause Off the Floor Conv Deadlift" to "Pause Off Floor Deadlift",
        "Block Pull" to "Block Pull",
        "Trap Bar Deadlift" to "Trap Bar Deadlift",
        "RDLs" to "RDLs",
        "DB RDLs" to "DB RDLs",
        "Deficit DB RDL" to "Deficit DB RDL",
        "SL RDL" to "Single Leg RDL",
        "Good Mornings" to "Good Mornings",
        "Barbell Hip Thrust" to "Barbell Hip Thrust",
        "Kettlebell Swing" to "Kettlebell Swing",
        "Timed KB Swing" to "Kettlebell Swing",
        "Back Raise" to "Back Raise",
        "Comp Bench" to "Comp Bench Press",
        "Comp Bench Press" to "Comp Bench Press",
        "Close Grip Bench Press" to "Close Grip Bench Press",
        "Wide Grip Bench Press" to "Wide Grip Bench Press",
        "Extra Wide Bench Press" to "Extra Wide Bench Press",
        "Incline Bench" to "Incline Bench Press",
        "Incline Bench Press" to "Incline Bench Press",
        "Pause Bench Press" to "Pause Bench Press",
        "3 Count Pause Bench" to "3 Count Pause Bench",
        "Spoto Press" to "Spoto Press",
        "Feet Up Bench" to "Feet Up Bench",
        "Floor Press" to "Floor Press",
        "Tempo Wide Grip Bench (5:0:0)" to "Tempo Bench Press",
        "Larsen Press" to "Larsen Press",
        "DB Bench Press" to "DB Bench Press",
        "DB Bench w/ Deep Stretch" to "DB Bench w/ Deep Stretch",
        "DB Incline Bench" to "DB Incline Bench",
        "DB Floor Press" to "DB Floor Press",
        "Dips" to "Dips",
        "Pushups w/ Deep Stretch" to "Pushups w/ Deep Stretch",
        "DB Fly" to "DB Fly",
        "Incline DB Fly" to "Incline DB Fly",
        "Pec Deck" to "Pec Deck",
        "Military Press" to "Military Press",
        "Push Press" to "Push Press",
        "DB Military Press" to "DB Military Press",
        "DB Arnold Press" to "DB Arnold Press",
        "Seated DB Press" to "Seated DB Press",
        "Kettlebell press" to "Kettlebell Press",
        "Landmine Press" to "Landmine Press",
        "DB Lateral Raise" to "DB Lateral Raise",
        "DB Front Raise" to "DB Front Raise",
        "DB Cuban Press" to "DB Cuban Press",
        "Bentover Rows" to "Barbell Row",
        "Barbell Row" to "Barbell Row",
        "Pendlay Row" to "Pendlay Row",
        "DB Rows" to "DB Rows",
        "Chest Supported Rows" to "Chest Supported Rows",
        "Seated Cable Row" to "Seated Cable Row",
        "1-Arm Cable Rows" to "1-Arm Cable Row",
        "T-Bar Row" to "T-Bar Row",
        "Meadows Row" to "Meadows Row",
        "Face Pulls" to "Face Pulls",
        "Band Pull-Apart" to "Band Pull-Apart",
        "Reverse Fly" to "Reverse Fly",
        "Pullups" to "Pull-ups",
        "Pull-ups" to "Pull-ups",
        "Weighted Pull-ups" to "Weighted Pull-ups",
        "Chin-ups" to "Chin-ups",
        "Lat Pulldowns" to "Lat Pulldowns",
        "1-Arm Lat Pull Downs" to "1-Arm Lat Pulldown",
        "Straight Arm Pulldown" to "Straight Arm Pulldown",
        "Barbell Curl" to "Barbell Curl",
        "EZ Bar Curls" to "EZ Bar Curl",
        "EZ Bar Curl" to "EZ Bar Curl",
        "DB Curls" to "DB Curls",
        "DB Alternating Curls" to "DB Alternating Curls",
        "Alternating Hammer Curl" to "Alternating Hammer Curl",
        "Concentration Curls" to "Concentration Curls",
        "Zottman Curls" to "Zottman Curls",
        "Tricep Pushdown" to "Tricep Pushdown",
        "1-Arm Tricep Pushdown" to "1-Arm Tricep Pushdown",
        "Tricep Kick Back" to "Tricep Kick Back",
        "Overhead Tricep Extension" to "Overhead Tricep Extension",
        "Barbell Skullcrushers" to "Barbell Skullcrushers",
        "Hamstring Curls" to "Hamstring Curls",
        "Calf Raises" to "Calf Raises",
        "Bent Knee Calf Raises" to "Bent Knee Calf Raises",
        "Hanging Leg Raises" to "Hanging Leg Raises",
        "Ab Wheel" to "Ab Wheel Rollout",
        "V-Ups" to "V-Ups",
        "Barbell Russian Twists" to "Barbell Russian Twists",
        "Landmine Rotation" to "Landmine Rotation",
        "Farmers Walk" to "Farmers Walk",
        "SA Farmers Walk" to "SA Farmers Walk",
    )

    private fun allExercises(): List<ExerciseData> = listOf(
        ExerciseData(
            id = "ex_comp_squat",
            name = "Comp Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE, MuscleGroup.HAMSTRINGS),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Set up with bar low on traps, in the shelf created by rear delts — not on the neck",
            "Take a stance slightly wider than shoulder-width, toes angled 30-45° outward to match hip anatomy",
            "Fill your belly with air and brace your entire core 360° — imagine bracing for a punch, not just pushing your belly forward",
            "Break hips and knees simultaneously — don't hinge first like an RDL",
            "Spread the floor apart with your feet; push your knees out hard in line with your toes throughout",
            "Descend until hip crease is clearly below the top of the knee — no question depth",
            "Drive out of the hole by pushing the floor away; hips and shoulders rise at the same rate",
            "Keep chest up; don't let the bar drift forward or hips shoot up first",
            "Think 'chest up and hips through' to finish the lockout — stand fully tall"
        ),
            isBarbell = true,
            minReps = 1,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_high_bar_squat",
            name = "High Bar Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Bar rests high on the traps, just below the neck — more upright torso than low-bar",
            "Narrower stance and more forward knee travel — great for developing quad strength",
            "Brace 360° and break hips and knees simultaneously",
            "Squat straight down between your legs — minimal hip hinge",
            "Knees track over toes; don't let them collapse inward",
            "Builds quad and upper back strength that transfers to the low-bar squat"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 8,
        ),
        ExerciseData(
            id = "ex_pause_high_bar_squat",
            name = "Pause High Bar Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Bar sits high on traps, more upright torso than low-bar — suits a narrower stance",
            "Pause at the bottom for prescribed time; resist any knee cave or forward lean",
            "Stay braced through the entire pause — do not relax your core",
            "Develop proprioception and strength in the most demanding position",
            "Drive knees out and chest up to stand from the paused position"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_pin_squat",
            name = "Pin Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Set pins at the desired depth — typically at or just below parallel",
            "Descend under control and come to a complete dead stop on the pins — no bounce",
            "Reset your brace fully on the pins, then drive up explosively",
            "Eliminates stretch reflex and builds starting strength at a specific joint angle",
            "Great for addressing sticking points at a particular ROM"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_safety_bar_squat",
            name = "Safety Bar Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE, MuscleGroup.UPPER_BACK),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.SAFETY_BAR,
            coachingCues = listOf(
            "Handles push forward, naturally forcing a more upright torso",
            "Great for upper back and core when bar or shoulder discomfort prevents low-bar",
            "Squat as you normally would but expect a significantly more upright torso",
            "Expect it to feel significantly harder than low-bar squat with the same load",
            "Drive elbows down to help stabilize the camber bar",
            "A powerful upper-back and quad builder"
        ),
            isBarbell = false,
            minReps = 3,
            maxReps = 8,
        ),
        ExerciseData(
            id = "ex_band_around_knees_goblet_squat",
            name = "Band Around Knees Goblet Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Press knees out against band",
            "Activates glute med",
            "Full depth with band tension"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_leg_press",
            name = "Leg Press",
            primaryMuscles = listOf(MuscleGroup.QUADS),
            secondaryMuscles = listOf(MuscleGroup.GLUTES),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Feet shoulder-width or wider, mid to upper portion of platform",
            "Lower until knees are at 90° or slightly below — stop before lower back rounds off the pad",
            "Don't lock knees at full extension — keep tension on the quads",
            "Slow eccentric (3-4 seconds) for hypertrophy stimulus",
            "Higher foot placement targets glutes and hamstrings more; lower placement hits quads"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_single_leg_leg_press",
            name = "Single Leg Leg Press",
            primaryMuscles = listOf(MuscleGroup.QUADS),
            secondaryMuscles = listOf(MuscleGroup.GLUTES),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "One foot centered on platform",
            "Full range of motion",
            "Don't let knee cave inward"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_bulgarian_split_squat",
            name = "Bulgarian Split Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.HAMSTRINGS),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Rear foot on the bench, laces down — not the heel; keep hip flexor relaxed",
            "Lean torso slightly forward for glute emphasis, or stay upright for quad emphasis",
            "Lower until rear knee nearly touches the floor for full range of motion",
            "Drive up through the front heel, keeping knee tracking over toes",
            "Expect significant delayed onset muscle soreness the first few times — dose volume carefully"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_walking_lunges",
            name = "Walking Lunges",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.HAMSTRINGS),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Long stride forward",
            "Keep torso upright",
            "Drive through front heel to step forward"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_pistol_squat",
            name = "Pistol Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Extend non-working leg forward",
            "Sit back and down with control",
            "Drive up through the heel"
        ),
            isBarbell = false,
            minReps = 3,
            maxReps = 8,
        ),
        ExerciseData(
            id = "ex_belt_squat",
            name = "Belt Squat",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.ADDUCTORS),
            movementPattern = MovementPattern.SQUAT,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Load is on the hips — no axial spinal loading; ideal for high-rep hypertrophy without spinal fatigue",
            "Stand on platforms so the weight can hang freely between your legs",
            "Stay upright, drive knees out, reach full depth",
            "Great for accumulation phases and back-down volume sets",
            "Focus on quad and glute drive — the absence of bar load lets you concentrate on leg strength"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_comp_deadlift",
            name = "Comp Deadlift",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.QUADS),
            secondaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Set up with bar over mid-foot (about 1 inch from shins), hip-width stance, toes slightly out",
            "Hinge to the bar — don't squat down to it; grip just outside your legs",
            "Take the slack out of the bar before pulling — you'll hear/feel a small click",
            "Wedge your hips down by pushing your knees out over your toes to create leg drive tension",
            "Take a big breath and brace your core 360° before the bar leaves the floor",
            "Think 'push the floor away' not 'pull the bar up' — engage your legs first",
            "Keep the bar dragging up your shins and thighs — any gap between bar and body loses efficiency",
            "At lockout, squeeze glutes and drive hips through — don't hyperextend the lower back",
            "Control the descent; don't drop the bar unless using bumper plates"
        ),
            isBarbell = true,
            minReps = 1,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_sumo_deadlift",
            name = "Sumo Deadlift",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
            secondaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Set up with a wide stance, toes pointed out 30-60° depending on hip anatomy — experiment to find your angle",
            "Grip narrows inside your knees — closer grip reduces range of motion",
            "Drop your hips and get your chest up — the more vertical your torso, the more leg drive you can use",
            "Push your knees hard out over your toes throughout the lift — 'spread the floor'",
            "The bar should travel straight up — stay over the bar, not behind it",
            "Drive hips to the bar, not hips up then forward",
            "Finish with hips fully extended and glutes squeezed — don't lean back",
            "Sumo benefits from hip mobility; spend time opening up hips in warm-up"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 8,
        ),
        ExerciseData(
            id = "ex_double_overhand_deficit_deadlift",
            name = "Double Overhand Deficit Deadlift",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.QUADS),
            secondaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.CORE, MuscleGroup.FOREARMS),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Double overhand grip (no hook, no straps) builds grip strength directly",
            "Stand on a 1-2 inch deficit — combined deficit and double overhand maximizes difficulty",
            "Squeeze the bar as hard as possible throughout the pull",
            "Use the same conventional pull mechanics — the grip and deficit are the variables",
            "Expect to use less weight than your strapped deficit work"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_halting_sumo_deadlift",
            name = "Halting Sumo Deadlift",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
            secondaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Pull to the prescribed height (usually knee) and hold for 2-3 seconds with sumo stance",
            "Don't let hips rise or back round during the pause — keep knees pushed out",
            "Tests and builds positional strength at that specific joint angle for sumo pullers",
            "Lower the bar under control or continue to lockout — follow programming",
            "Identifies and trains weaknesses at the exact sticking point position"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_block_pull",
            name = "Block Pull",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.UPPER_BACK),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Bar elevated on blocks — typically at or just above knee height",
            "Use your competition stance and grip",
            "Focus on the lockout: squeeze glutes and drive hips aggressively through at the top",
            "Can be loaded supramaximally to train the top portion of the deadlift",
            "Drive hips forward — don't lean back excessively at lockout"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_rdls",
            name = "RDLs",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Start from a standing position — this is NOT a deadlift from the floor",
            "Slight knee bend maintained throughout the entire movement",
            "Push hips back, keeping bar dragging down the thighs",
            "Lower until you feel a strong hamstring stretch — usually mid-shin for most lifters",
            "Squeeze glutes to drive hips forward to lockout — don't hyperextend at the top",
            "Never round the lower back — if you feel lumbar strain, reduce range of motion"
        ),
            isBarbell = true,
            minReps = 6,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_deficit_db_rdl",
            name = "Deficit DB RDL",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Stand on small platform for extra ROM",
            "Greater hamstring stretch at bottom",
            "Control the descent"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_stiff_leg_deadlift",
            name = "Stiff Leg Deadlift",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Legs nearly straight — very slight bend at the knee, maintained throughout",
            "Hinge at the hips, lowering the bar close to the legs",
            "Maximally loads the hamstrings through a long range of motion",
            "Stop before lower back rounds — prioritize hamstring stretch over depth",
            "Drive hips forward to return, squeezing glutes at the top"
        ),
            isBarbell = true,
            minReps = 6,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_barbell_hip_thrust",
            name = "Barbell Hip Thrust",
            primaryMuscles = listOf(MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.HAMSTRINGS),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Upper back on bench, feet hip-width and flat on floor, bar padded at hip crease",
            "Drive through the heels; at the top, body forms a straight line from shoulders to knees",
            "Don't hyperextend the lower back at the top — full hip extension is sufficient",
            "Chin tucked throughout — don't let the head fall back",
            "Squeeze glutes hard at the top of every rep for maximum activation"
        ),
            isBarbell = true,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_glute_bridge",
            name = "Glute Bridge",
            primaryMuscles = listOf(MuscleGroup.GLUTES),
            secondaryMuscles = listOf(MuscleGroup.HAMSTRINGS),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Lie on your back, feet flat on the floor hip-width apart, knees bent 90°",
            "Drive through the heels to lift hips — squeeze glutes at the top",
            "Hips form a straight line with knees and shoulders at the top",
            "Don't hyperextend the lower back — focus on glute contraction, not height",
            "Hold the top position for a count to maximize glute activation"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_kettlebell_swing",
            name = "Kettlebell Swing",
            primaryMuscles = listOf(MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.KETTLEBELL,
            coachingCues = listOf(
            "Hinge, don't squat",
            "Snap hips forward explosively",
            "Arms are just along for the ride"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_reverse_hyperextension",
            name = "Reverse Hyperextension",
            primaryMuscles = listOf(MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Lie face down on the pad with hips at the edge — anchor upper body firmly",
            "Swing legs up using glutes and hamstrings — not momentum alone",
            "At the top, squeeze glutes hard; don't hyperextend the lower back excessively",
            "Lower legs under control — resist gravity on the way down",
            "Excellent for posterior chain hypertrophy with minimal spinal compression"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_sumo_deficit_deadlift",
            name = "Sumo Deficit Deadlift",
            primaryMuscles = listOf(MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS),
            secondaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Stand on a 1-2 inch deficit with your sumo setup — wider stance, toes flared",
            "Increases the range of motion and demands more hip mobility and depth",
            "Keep the same sumo technique — hips dropped, chest up, knees out",
            "Don't let the extra depth cause knee cave or loss of torso position",
            "Builds starting strength for the sumo pull directly"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_reverse_band_deadlift",
            name = "Reverse Band Deadlift",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.UPPER_BACK),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.HINGE,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Bands attached overhead deload the bar at the bottom, adding resistance at lockout",
            "Use your competition stance and technique — treat it like any other deadlift",
            "Be aggressive at the top where bands provide maximum resistance",
            "Good for training through sticking points in the upper half of the pull",
            "The accommodating resistance teaches you to accelerate through the whole lift"
        ),
            isBarbell = true,
            minReps = 1,
            maxReps = 5,
        ),
        ExerciseData(
            id = "ex_comp_bench_press",
            name = "Comp Bench Press",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Set up with eyes under the bar; grip so wrists are straight and bar sits in the heel of the palm",
            "Retract shoulder blades hard and depress them — create a stable shelf; maintain this throughout",
            "Arch your upper back to reduce range of motion; feet flat on floor creating leg drive",
            "Unrack by pressing the bar over your chest — do not press it forward and lose position",
            "Lower the bar with your lats in a controlled arc to just below the nipple line (not the sternum)",
            "On touch, keep elbows at 45-75° from the torso — not fully flared, not fully tucked",
            "Drive legs into the floor, transferring force through your arched back into the bar",
            "Press the bar in a slight diagonal — backward toward the rack as you push up",
            "Lock out with hips on the bench; maintain the arch until bar is reracked"
        ),
            isBarbell = true,
            minReps = 1,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_wide_grip_bench_press",
            name = "Wide Grip Bench Press",
            primaryMuscles = listOf(MuscleGroup.CHEST),
            secondaryMuscles = listOf(MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Grip 1-2 inches wider than competition grip — reduces range of motion slightly",
            "Greater pectoral stretch at the bottom; trains off-chest strength",
            "Keep elbows from flaring more than slightly — protect the shoulder",
            "Touch the same spot as your competition bench — don't change touch point",
            "Use this to build chest strength that supports competition bench performance"
        ),
            isBarbell = true,
            minReps = 5,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_incline_bench_press",
            name = "Incline Bench Press",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.SHOULDERS),
            secondaryMuscles = listOf(MuscleGroup.TRICEPS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Set bench to 30-45° — higher angles reduce pec and increase shoulder involvement",
            "Lower to upper chest and clavicle area — higher touch point than flat bench",
            "Greater front deltoid and upper pec involvement than flat bench",
            "Keep scapulae retracted and depressed despite the incline angle",
            "Control the descent — the incline makes it easy to lose position"
        ),
            isBarbell = true,
            minReps = 5,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_pause_bench_press",
            name = "Pause Bench Press",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Touch the bar to the chest and hold for 1-2 seconds — or as prescribed",
            "Stay completely tight during the pause — don't let the bar sink into your chest",
            "Keep legs driving into the floor throughout the pause",
            "Drive explosively off the pause — no counter-movement",
            "Builds starting strength and teaches the proper bottom position"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_spoto_press",
            name = "Spoto Press",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Lower the bar to 1 inch above the chest — pause there without touching",
            "Requires significant tension and control; builds the 1-2 inch off chest range",
            "Teaches you to stay tight at the bottom without relying on chest contact",
            "This is harder than it sounds — the no-touch point is the weakest position for most",
            "Control the descent carefully — the stop must be deliberate, not a bounce"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_floor_press",
            name = "Floor Press",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Lie on the floor and lower the bar until your upper arms touch the floor — pause there",
            "No leg drive (legs extended straight); all press from your upper body",
            "Builds pure pressing strength from the mid-range and lockout",
            "Great for triceps and mid-range bench strength",
            "The floor acts like a pin — don't bounce off the floor"
        ),
            isBarbell = true,
            minReps = 5,
            maxReps = 8,
        ),
        ExerciseData(
            id = "ex_larsen_press",
            name = "Larsen Press",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Feet lifted off the floor — legs extended or raised; eliminates all leg drive",
            "Forces the upper body to generate all pressing force without lower body assistance",
            "Excellent for identifying upper body weaknesses masked by leg drive",
            "Keep arch and shoulder blade position — just remove the foot drive",
            "Expect to press significantly less than your regular bench"
        ),
            isBarbell = true,
            minReps = 5,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_db_bench_w__deep_stretch",
            name = "DB Bench w/ Deep Stretch",
            primaryMuscles = listOf(MuscleGroup.CHEST),
            secondaryMuscles = listOf(MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Lower DBs deeper than normal",
            "Emphasize the stretch at bottom",
            "Control the descent"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_db_floor_press",
            name = "DB Floor Press",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Lie on floor with DBs",
            "Elbows touch floor at bottom",
            "Press up from dead stop"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_weighted_dips",
            name = "Weighted Dips",
            primaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Lean forward slightly for chest, upright for triceps — same principle as bodyweight dips",
            "Lower until upper arms are at or below parallel for full range of motion",
            "Keep elbows from flaring excessively throughout the movement",
            "Drive up through the palm, fully extending the elbow at the top",
            "Control the descent — weighted dips have serious injury potential if rushed"
        ),
            isBarbell = false,
            minReps = 5,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_pushups_w__deep_stretch",
            name = "Pushups w/ Deep Stretch",
            primaryMuscles = listOf(MuscleGroup.CHEST),
            secondaryMuscles = listOf(MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Hands on elevated surface for deeper ROM",
            "Emphasize chest stretch at bottom",
            "Control the movement"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_incline_db_fly",
            name = "Incline DB Fly",
            primaryMuscles = listOf(MuscleGroup.CHEST),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "30 degree incline",
            "Arc the DBs out and down",
            "Feel upper chest stretch"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_pec_deck",
            name = "Pec Deck",
            primaryMuscles = listOf(MuscleGroup.CHEST),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Elbows at 90 degrees on pads",
            "Squeeze pads together",
            "Control the return"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_pin_press",
            name = "Pin Press",
            primaryMuscles = listOf(MuscleGroup.TRICEPS, MuscleGroup.CHEST),
            secondaryMuscles = listOf(MuscleGroup.SHOULDERS),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Set pins at desired height (chest or mid-range)",
            "Come to full dead stop on pins",
            "Brace hard then press explosively",
            "Eliminates stretch reflex, builds pure pressing strength"
        ),
            isBarbell = true,
            minReps = 3,
            maxReps = 6,
        ),
        ExerciseData(
            id = "ex_jm_press",
            name = "JM Press",
            primaryMuscles = listOf(MuscleGroup.TRICEPS),
            secondaryMuscles = listOf(MuscleGroup.CHEST),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Hands slightly inside shoulder width",
            "Lower bar toward throat/upper chest",
            "Elbows flare slightly forward",
            "Press back to lockout using triceps"
        ),
            isBarbell = true,
            minReps = 6,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_tate_press",
            name = "Tate Press",
            primaryMuscles = listOf(MuscleGroup.TRICEPS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.HORIZONTAL_PUSH,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "DBs start over chest, elbows flared out",
            "Lower DBs by bending elbows outward",
            "Press back to start with triceps",
            "Effective lockout tricep isolation"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_military_press",
            name = "Military Press",
            primaryMuscles = listOf(MuscleGroup.SHOULDERS),
            secondaryMuscles = listOf(MuscleGroup.TRICEPS),
            movementPattern = MovementPattern.VERTICAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Clean grip just outside shoulders; bar starts at front delts in the rack position",
            "Squeeze glutes and brace core hard for lumbar stability — don't hyperextend the lower back",
            "Press straight up; move your head slightly back to clear the bar, then forward at lockout",
            "Bar path ends slightly behind the ear line when viewed from the side — over mid-foot",
            "Full lockout on every rep — don't cut the range of motion short",
            "The core and glutes are the foundation — stay stiff from feet to hands"
        ),
            isBarbell = true,
            minReps = 5,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_db_military_press",
            name = "DB Military Press",
            primaryMuscles = listOf(MuscleGroup.SHOULDERS),
            secondaryMuscles = listOf(MuscleGroup.TRICEPS),
            movementPattern = MovementPattern.VERTICAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Dumbbells at ear height, elbows slightly forward of the body — not directly to the sides",
            "Press straight up and allow wrists to naturally rotate slightly at the top",
            "Full lockout at the top; control the descent back to starting position",
            "Core braced to prevent lower back hyperextension — don't lean back",
            "Greater range of motion than barbell; allows natural wrist and elbow tracking"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_seated_db_press",
            name = "Seated DB Press",
            primaryMuscles = listOf(MuscleGroup.SHOULDERS),
            secondaryMuscles = listOf(MuscleGroup.TRICEPS),
            movementPattern = MovementPattern.VERTICAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Seated with back support",
            "Press DBs straight up",
            "Lower to shoulder height"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_landmine_press",
            name = "Landmine Press",
            primaryMuscles = listOf(MuscleGroup.SHOULDERS),
            secondaryMuscles = listOf(MuscleGroup.CHEST, MuscleGroup.TRICEPS),
            movementPattern = MovementPattern.VERTICAL_PUSH,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "One end of barbell in corner/landmine",
            "Press up and forward",
            "Great for shoulder-friendly pressing"
        ),
            isBarbell = true,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_cable_lateral_raise",
            name = "Cable Lateral Raise",
            primaryMuscles = listOf(MuscleGroup.SHOULDERS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.VERTICAL_PUSH,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Cable at opposite side",
            "Raise to shoulder height",
            "Constant tension from cable"
        ),
            isBarbell = false,
            minReps = 12,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_db_cuban_press",
            name = "DB Cuban Press",
            primaryMuscles = listOf(MuscleGroup.SHOULDERS, MuscleGroup.REAR_DELTS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.VERTICAL_PUSH,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Upright row to external rotation to press",
            "Light weight, focus on rotator cuff",
            "Control each phase"
        ),
            isBarbell = false,
            minReps = 12,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_barbell_row",
            name = "Barbell Row",
            primaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.LATS),
            secondaryMuscles = listOf(MuscleGroup.BICEPS),
            movementPattern = MovementPattern.HORIZONTAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Hinge to 45° or more — the more horizontal, the more lat-focused the row",
            "Overhand grip for more upper back; underhand for more bicep and lower lat",
            "Pull bar to lower chest or upper belly depending on grip and torso angle",
            "Squeeze shoulder blades together at the top of each rep",
            "Lower with control — don't just drop the bar"
        ),
            isBarbell = true,
            minReps = 5,
            maxReps = 10,
        ),
        ExerciseData(
            id = "ex_db_rows",
            name = "DB Rows",
            primaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.LATS),
            secondaryMuscles = listOf(MuscleGroup.BICEPS),
            movementPattern = MovementPattern.HORIZONTAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Brace one hand and knee on a bench; torso parallel to the floor",
            "Let the dumbbell hang with full arm extension at the bottom",
            "Drive the elbow straight up, pulling the dumbbell to your hip",
            "Squeeze the lat at the top; full shoulder retraction",
            "Don't rotate the torso excessively — keep the movement in the lat"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_seated_cable_row",
            name = "Seated Cable Row",
            primaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.LATS),
            secondaryMuscles = listOf(MuscleGroup.BICEPS),
            movementPattern = MovementPattern.HORIZONTAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Sit tall with a slight hip hinge — don't slouch into the movement",
            "Full arm extension at the start — feel the lat stretch",
            "Pull handle to lower sternum, driving elbows back behind the torso",
            "Squeeze shoulder blades at the top; control the return",
            "Don't use momentum or excessively lean back — keep the movement strict"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_t_bar_row",
            name = "T-Bar Row",
            primaryMuscles = listOf(MuscleGroup.UPPER_BACK, MuscleGroup.LATS),
            secondaryMuscles = listOf(MuscleGroup.BICEPS),
            movementPattern = MovementPattern.HORIZONTAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Straddle the bar",
            "Pull to chest",
            "Keep chest up"
        ),
            isBarbell = true,
            minReps = 6,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_machine_row",
            name = "Machine Row",
            primaryMuscles = listOf(MuscleGroup.UPPER_BACK),
            secondaryMuscles = listOf(MuscleGroup.BICEPS),
            movementPattern = MovementPattern.HORIZONTAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Chest against pad",
            "Pull handles to torso",
            "Squeeze at end range"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_band_pull_apart",
            name = "Band Pull-Apart",
            primaryMuscles = listOf(MuscleGroup.REAR_DELTS, MuscleGroup.UPPER_BACK),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.HORIZONTAL_PULL,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BAND,
            coachingCues = listOf(
            "Arms extended, band at chest height",
            "Pull apart squeezing rear delts",
            "Control the return"
        ),
            isBarbell = false,
            minReps = 15,
            maxReps = 25,
        ),
        ExerciseData(
            id = "ex_pull_ups",
            name = "Pull-ups",
            primaryMuscles = listOf(MuscleGroup.LATS),
            secondaryMuscles = listOf(MuscleGroup.BICEPS, MuscleGroup.UPPER_BACK),
            movementPattern = MovementPattern.VERTICAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Overhand grip shoulder-width or wider; dead hang at the bottom — full scapular depression",
            "Pull until chin clearly clears the bar",
            "Think 'elbows to back pockets' to maximize lat engagement",
            "Avoid excessive kipping — controlled reps build more strength",
            "Control the descent fully — the eccentric is half the work"
        ),
            isBarbell = false,
            minReps = 5,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_chin_ups",
            name = "Chin-ups",
            primaryMuscles = listOf(MuscleGroup.LATS, MuscleGroup.BICEPS),
            secondaryMuscles = listOf(MuscleGroup.UPPER_BACK),
            movementPattern = MovementPattern.VERTICAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Supinated (underhand) grip at shoulder width or slightly narrower",
            "Dead hang at the bottom — full arm extension and scapular depression",
            "Pull chin above the bar; biceps and lats both contribute strongly",
            "Control the descent — avoid swinging or kipping",
            "The supinated grip places the biceps in a stronger position than pull-ups"
        ),
            isBarbell = false,
            minReps = 5,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_close_grip_lat_pulldown",
            name = "Close Grip Lat Pulldown",
            primaryMuscles = listOf(MuscleGroup.LATS),
            secondaryMuscles = listOf(MuscleGroup.BICEPS),
            movementPattern = MovementPattern.VERTICAL_PULL,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Narrow/V-bar grip",
            "Pull to upper chest",
            "More biceps involvement"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_straight_arm_pulldown",
            name = "Straight Arm Pulldown",
            primaryMuscles = listOf(MuscleGroup.LATS),
            secondaryMuscles = listOf(MuscleGroup.CORE),
            movementPattern = MovementPattern.VERTICAL_PULL,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Arms straight, slight elbow bend",
            "Pull bar down to thighs",
            "Feel lat stretch overhead"
        ),
            isBarbell = false,
            minReps = 12,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_barbell_curl",
            name = "Barbell Curl",
            primaryMuscles = listOf(MuscleGroup.BICEPS),
            secondaryMuscles = listOf(MuscleGroup.FOREARMS),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Elbows pinned to sides throughout — don't let them drift forward or back",
            "Full range of motion: start with arms nearly straight, curl to peak contraction",
            "Squeeze the bicep hard at the top of every rep",
            "Control the descent — the eccentric builds as much or more muscle than the concentric",
            "Don't swing the body — momentum reduces bicep tension"
        ),
            isBarbell = true,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_db_curls",
            name = "DB Curls",
            primaryMuscles = listOf(MuscleGroup.BICEPS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Elbows pinned to sides; supinate the wrist (rotate palm up) as you curl",
            "Full range of motion from near-full extension to peak contraction",
            "Squeeze the bicep at the top; control the eccentric",
            "Alternate arms or both together — both approaches are effective",
            "Don't swing — isolate the bicep by keeping upper arms stationary"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_alternating_hammer_curl",
            name = "Alternating Hammer Curl",
            primaryMuscles = listOf(MuscleGroup.BICEPS),
            secondaryMuscles = listOf(MuscleGroup.FOREARMS),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Neutral grip (thumbs up) throughout — don't rotate the wrist",
            "Targets the brachialis and brachioradialis more than supinated curls",
            "Full range of motion; elbows pinned to sides",
            "Control the descent to maximize muscle stimulus",
            "Builds arm thickness and elbow flexor strength that transfers to pulling movements"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_incline_db_curl",
            name = "Incline DB Curl",
            primaryMuscles = listOf(MuscleGroup.BICEPS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Incline bench 45°, arms hanging",
            "Greater stretch on biceps",
            "Curl up with control"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_cable_curl",
            name = "Cable Curl",
            primaryMuscles = listOf(MuscleGroup.BICEPS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Constant tension from cable",
            "Elbows at sides",
            "Squeeze at the top"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_tricep_pushdown",
            name = "Tricep Pushdown",
            primaryMuscles = listOf(MuscleGroup.TRICEPS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Elbows pinned to sides — don't let them flare or drift forward",
            "Full extension at the bottom — squeeze triceps at the peak contraction",
            "Control the return to the start position — don't let the stack pull your arms up",
            "Use a variety of attachments (rope, bar, single handle) to vary stimulus",
            "Focus on feeling the tricep contract, not just moving the weight"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_tricep_kick_back",
            name = "Tricep Kick Back",
            primaryMuscles = listOf(MuscleGroup.TRICEPS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Hinge forward, upper arm parallel to floor",
            "Extend forearm back",
            "Squeeze at full extension"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_barbell_skullcrushers",
            name = "Barbell Skullcrushers",
            primaryMuscles = listOf(MuscleGroup.TRICEPS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Lower bar to forehead or behind the head — behind-head position increases ROM",
            "Elbows pointed toward the ceiling — keep them there; don't let them flare",
            "Only the forearms move — upper arms stay stationary",
            "Extend to full lockout on each rep",
            "Control the descent carefully; EZ bar reduces wrist stress compared to straight bar"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 12,
        ),
        ExerciseData(
            id = "ex_wrist_curls",
            name = "Wrist Curls",
            primaryMuscles = listOf(MuscleGroup.FOREARMS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Forearms on bench, wrists hanging off",
            "Curl wrists up",
            "Control the descent"
        ),
            isBarbell = true,
            minReps = 15,
            maxReps = 25,
        ),
        ExerciseData(
            id = "ex_farmers_walk",
            name = "Farmers Walk",
            primaryMuscles = listOf(MuscleGroup.FOREARMS),
            secondaryMuscles = listOf(MuscleGroup.CORE, MuscleGroup.UPPER_BACK),
            movementPattern = MovementPattern.ISOLATION_ARMS,
            classification = ExerciseClassification.COMPOUND,
            equipment = EquipmentType.DUMBBELL,
            coachingCues = listOf(
            "Heavy DBs at sides",
            "Walk with tall posture",
            "Grip hard, shoulders back"
        ),
            isBarbell = false,
            minReps = 1,
            maxReps = 1,
        ),
        ExerciseData(
            id = "ex_leg_extensions",
            name = "Leg Extensions",
            primaryMuscles = listOf(MuscleGroup.QUADS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_LEGS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Sit with back against the pad, knee at the pivot point of the machine",
            "Extend to full lockout — squeeze the quad hard at the top",
            "Control the descent — don't let the weight snap your knee",
            "The terminal extension (last 10°) is where quad contraction is greatest",
            "Single-leg variations help identify and address imbalances"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_hamstring_curls",
            name = "Hamstring Curls",
            primaryMuscles = listOf(MuscleGroup.HAMSTRINGS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_LEGS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Lie prone with knees at the pivot point; toes neutral or slightly inward",
            "Curl until hamstrings are fully contracted — heels toward glutes",
            "Control the descent — resist the weight on the way down",
            "Don't let hips lift off the pad — keep contact with the machine",
            "Full range of motion for maximum hamstring development"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_seated_calf_raises",
            name = "Seated Calf Raises",
            primaryMuscles = listOf(MuscleGroup.CALVES),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_LEGS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Seated position with knees bent targets the soleus — different from standing calf raises",
            "Full range of motion: full stretch at the bottom, full contraction at the top",
            "Slow the eccentric — pause at the bottom to eliminate bounce",
            "Pause at the top and squeeze the calf hard before lowering",
            "Calves respond well to high rep ranges (15-25+)"
        ),
            isBarbell = false,
            minReps = 12,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_adductor_machine",
            name = "Adductor Machine",
            primaryMuscles = listOf(MuscleGroup.ADDUCTORS),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_LEGS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.MACHINE,
            coachingCues = listOf(
            "Squeeze legs together",
            "Control the return",
            "Don't use momentum"
        ),
            isBarbell = false,
            minReps = 12,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_glute_kickback",
            name = "Glute Kickback",
            primaryMuscles = listOf(MuscleGroup.GLUTES),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.ISOLATION_LEGS,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Cable at ankle",
            "Kick back squeezing glute",
            "Don't arch lower back"
        ),
            isBarbell = false,
            minReps = 12,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_hanging_leg_raises",
            name = "Hanging Leg Raises",
            primaryMuscles = listOf(MuscleGroup.CORE),
            secondaryMuscles = listOf(MuscleGroup.HIP_FLEXORS),
            movementPattern = MovementPattern.CORE,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Hang from bar, legs straight",
            "Raise legs to 90° or higher",
            "Lower with control, don't swing"
        ),
            isBarbell = false,
            minReps = 8,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_v_ups",
            name = "V-Ups",
            primaryMuscles = listOf(MuscleGroup.CORE),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.CORE,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Lie flat, arms extended overhead",
            "Simultaneously raise legs and torso",
            "Touch hands to feet at top"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 20,
        ),
        ExerciseData(
            id = "ex_pallof_press",
            name = "Pallof Press",
            primaryMuscles = listOf(MuscleGroup.CORE),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.CORE,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.CABLE,
            coachingCues = listOf(
            "Stand perpendicular to cable",
            "Press hands straight out",
            "Resist rotation"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_barbell_russian_twists",
            name = "Barbell Russian Twists",
            primaryMuscles = listOf(MuscleGroup.CORE),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.CORE,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BARBELL,
            coachingCues = listOf(
            "Landmine setup, press bar out",
            "Rotate side to side",
            "Keep arms extended"
        ),
            isBarbell = true,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_dead_bug",
            name = "Dead Bug",
            primaryMuscles = listOf(MuscleGroup.CORE),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.CORE,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Back flat on floor",
            "Extend opposite arm and leg",
            "Keep lower back pressed down"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 15,
        ),
        ExerciseData(
            id = "ex_decline_sit_ups",
            name = "Decline Sit-ups",
            primaryMuscles = listOf(MuscleGroup.CORE),
            secondaryMuscles = emptyList(),
            movementPattern = MovementPattern.CORE,
            classification = ExerciseClassification.ISOLATION,
            equipment = EquipmentType.BODYWEIGHT,
            coachingCues = listOf(
            "Feet locked on decline bench",
            "Curl up using abs",
            "Don't use hip flexors to pull up"
        ),
            isBarbell = false,
            minReps = 10,
            maxReps = 20,
        ),
    )
}
